# Generated by Django 5.1.1 on 2024-09-18 21:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="patient",
            unique_together={("first_name", "last_name", "date_of_birth")},
        ),
    ]
