# Generated by Django 5.1.1 on 2024-09-26 22:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0002_alter_patient_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="lab_tests",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="vital_signs",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="weight",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
